### ISSUE TITLE
Full Path yerine Relative Path

### ISSUE THREAD

**Issue by ileri** [ozcakircankat/youtube_mp4#2]
youtubeindirici.py dosyasındaki kodda ikon yolu bildiren
 `self.setWindowIcon(QIcon("C:/Users/AYTEN/Desktop/mp4.ico"))`
 ifadesi ico dosyasının **Full Path** yani senin bilgisayarındaki tam yolunu gösteriyor. 
Bunun yerine ico dosyasını kodun olduğu dizine alarak , yada kodun olduğu dizinde **"src"** , **"img"** yada **"images"** gibi bir dizin oluşturarak onun içine atıp koddaki full path i de **relative path** ile değiştirirsen daha sağlıklı olacaktır.
Örneğin **"./images/mp4.ico"** gibi bir yazım kodunun mobilizasyonunu sağlayacaktır.

**Comment by ozcakircankat** [comment]
Haklısınız, bu sorunu diğer projelerimde de yaşadım dediğinizi yapacağım. Uyarınız için çok teşekkür ederim.
